

// Generated by cosim_wrapper.pl to be used for cosim

module errorDetect_cosim_wrapper(interface In, interface Error, interface Out, input _RESET);

 errorDetect errorDetect_expanded (Error.d[0][0] , Error.d[1][0] , In.e[0] , In.e[1] , In.e[2] , In.e[3] 
 , In.e[4] , In.e[5] , In.e[6] , In.e[7] , In.e[8] , Out.d[0][0] 
 , Out.d[0][1] , Out.d[0][2] , Out.d[0][3] , Out.d[0][4] , Out.d[0][5] , Out.d[0][6] 
 , Out.d[0][7] , Out.d[0][8] , Out.d[1][0] , Out.d[1][1] , Out.d[1][2] , Out.d[1][3] 
 , Out.d[1][4] , Out.d[1][5] , Out.d[1][6] , Out.d[1][7] , Out.d[1][8] , Error.e[0] 
 , In.d[0][0] , In.d[0][1] , In.d[0][2] , In.d[0][3] , In.d[0][4] , In.d[0][5] 
 , In.d[0][6] , In.d[0][7] , In.d[0][8] , In.d[1][0] , In.d[1][1] , In.d[1][2] 
 , In.d[1][3] , In.d[1][4] , In.d[1][5] , In.d[1][6] , In.d[1][7] , In.d[1][8] 
 , Out.e[0] , Out.e[1] , Out.e[2] , Out.e[3] , Out.e[4] , Out.e[5] 
 , Out.e[6] , Out.e[7] , Out.e[8] , _RESET );

endmodule

// Generated by E-GRAPH (EGS) v0.01

module errorDetect (\Error_d[0][0] , \Error_d[1][0] , \In_e[0] , \In_e[1] , \In_e[2] , \In_e[3] , \In_e[4] , \In_e[5] , 
  \In_e[6] , \In_e[7] , \In_e[8] , \Out_d[0][0] , \Out_d[0][1] , \Out_d[0][2] , \Out_d[0][3] , \Out_d[0][4] , \Out_d[0][5] , 
  \Out_d[0][6] , \Out_d[0][7] , \Out_d[0][8] , \Out_d[1][0] , \Out_d[1][1] , \Out_d[1][2] , \Out_d[1][3] , \Out_d[1][4] , 
  \Out_d[1][5] , \Out_d[1][6] , \Out_d[1][7] , \Out_d[1][8] , \Error_e , \In_d[0][0] , \In_d[0][1] , \In_d[0][2] , \In_d[0][3] , 
  \In_d[0][4] , \In_d[0][5] , \In_d[0][6] , \In_d[0][7] , \In_d[0][8] , \In_d[1][0] , \In_d[1][1] , \In_d[1][2] , \In_d[1][3] , 
  \In_d[1][4] , \In_d[1][5] , \In_d[1][6] , \In_d[1][7] , \In_d[1][8] , \Out_e[0] , \Out_e[1] , \Out_e[2] , \Out_e[3] , 
  \Out_e[4] , \Out_e[5] , \Out_e[6] , \Out_e[7] , \Out_e[8] , _RESET );
  input  \Error_e , \In_d[0][0] , \In_d[0][1] , \In_d[0][2] , \In_d[0][3] , \In_d[0][4] , \In_d[0][5] , \In_d[0][6] ;
  input  \In_d[0][7] , \In_d[0][8] , \In_d[1][0] , \In_d[1][1] , \In_d[1][2] , \In_d[1][3] , \In_d[1][4] , \In_d[1][5] ;
  input  \In_d[1][6] , \In_d[1][7] , \In_d[1][8] , \Out_e[0] , \Out_e[1] , \Out_e[2] , \Out_e[3] , \Out_e[4] , \Out_e[5] ;
  input  \Out_e[6] , \Out_e[7] , \Out_e[8] , _RESET ;

  output \Error_d[0][0] , \Error_d[1][0] , \In_e[0] , \In_e[1] , \In_e[2] , \In_e[3] , \In_e[4] , \In_e[5] , \In_e[6] ;
  output \In_e[7] , \In_e[8] , \Out_d[0][0] , \Out_d[0][1] , \Out_d[0][2] , \Out_d[0][3] , \Out_d[0][4] , \Out_d[0][5] ;
  output \Out_d[0][6] , \Out_d[0][7] , \Out_d[0][8] , \Out_d[1][0] , \Out_d[1][1] , \Out_d[1][2] , \Out_d[1][3] , \Out_d[1][4] ;
  output \Out_d[1][5] , \Out_d[1][6] , \Out_d[1][7] , \Out_d[1][8] ;

  wire   \Error_d[0][0] , \Error_d[1][0] , \In_e[0] , \In_e[1] , \In_e[2] , \In_e[3] , \In_e[4] , \In_e[5] , \In_e[6] ;
  wire   \In_e[7] , \In_e[8] , \Out_d[0][0] , \Out_d[0][1] , \Out_d[0][2] , \Out_d[0][3] , \Out_d[0][4] , \Out_d[0][5] ;
  wire   \Out_d[0][6] , \Out_d[0][7] , \Out_d[0][8] , \Out_d[1][0] , \Out_d[1][1] , \Out_d[1][2] , \Out_d[1][3] , \Out_d[1][4] ;
  wire   \Out_d[1][5] , \Out_d[1][6] , \Out_d[1][7] , \Out_d[1][8] , \d[0].0 , \d[0].1 , \d[0]_15.e , \d[1].0 , \d[1].1 ;
  wire   \d[1]_16.e , \d[2].0 , \d[2].1 , \d[2]_17.e , \d[3].0 , \d[3].1 , \d[3]_18.e , \d[4].0 , \d[4].1 , \d[4]_19.e ;
  wire   \d[5].0 , \d[5].1 , \d[5]_20.e , \d[6].0 , \d[6].1 , \d[6]_21.e , \d[7].0 , \d[7].1 , \d[7]_22.e , \d[8].0 , \d[8].1 ;
  wire   \d[8]_23.e , \errorDetect_RTL_BODY.n_0.0 , \errorDetect_RTL_BODY.n_0.1 , \errorDetect_RTL_BODY.n_1.0 ;
  wire   \errorDetect_RTL_BODY.n_1.1 , \errorDetect_RTL_BODY.n_2.0 , \errorDetect_RTL_BODY.n_2.1 , \errorDetect_RTL_BODY.n_3.0 ;
  wire   \errorDetect_RTL_BODY.n_3.1 , \n_36.0 , \n_36.1 , \n_36.e , \pchb_cloud_0_inst_go , \pchb_cloud_0_inst_valid_out_0 ;
  wire   \pchb_cloud_24_inst_go , \pchb_cloud_24_inst_valid_out_0 , \pchb_cloud_24_inst_valid_out_1 , \pchb_cloud_3_inst_go ;
  wire   \pchb_cloud_3_inst_valid_out_0 , \pchb_cloud_4_inst_go , \pchb_cloud_4_inst_valid_out_0 ;

  trireg \c0.e , \c24.e , \c3.e , \c4.e , \pchb_cloud_0_inst_en0 , \pchb_cloud_10_inst_en0 , \pchb_cloud_11_inst_en0 ;
  trireg \pchb_cloud_12_inst_en0 , \pchb_cloud_13_inst_en0 , \pchb_cloud_24_inst_en0 , \pchb_cloud_3_inst_en0 ;
  trireg \pchb_cloud_4_inst_en0 , \pchb_cloud_5_inst_en0 , \pchb_cloud_6_inst_en0 , \pchb_cloud_7_inst_en0 ;
  trireg \pchb_cloud_8_inst_en0 , \pchb_cloud_9_inst_en0 ;



  \synthesis.qdi.logic3.LOGIC3_69.2 \errorDetect_RTL_BODY.g91 ( 
    .V ( \pchb_cloud_0_inst_valid_out_0 ), 
    .en ( \pchb_cloud_0_inst_en0 ), 
    .\A[0].0 ( \errorDetect_RTL_BODY.n_1.0 ), 
    .\A[0].1 ( \errorDetect_RTL_BODY.n_1.1 ), 
    .\A[1].0 ( \errorDetect_RTL_BODY.n_2.0 ), 
    .\A[1].1 ( \errorDetect_RTL_BODY.n_2.1 ), 
    .\A[2].0 ( \errorDetect_RTL_BODY.n_3.0 ), 
    .\A[2].1 ( \errorDetect_RTL_BODY.n_3.1 ), 
    .\X.0 ( \n_36.0 ), 
    .\X.1 ( \n_36.1 ));
  \synthesis.qdi.special.CTREE2.2 \ctreeerrorDetect_RTL_BODY.g91 ( 
    .x ( \pchb_cloud_0_inst_en0 ), 
    .\a[0] ( \pchb_cloud_0_inst_go ), 
    .\a[1] ( \n_36.e ));
  \synthesis.qdi.special.CTRL31.2 \pchb_cloud_0_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_0_inst_go ), 
    .Ae ( \c0.e ), 
    .\A[0].0 ( \errorDetect_RTL_BODY.n_1.0 ), 
    .\A[0].1 ( \errorDetect_RTL_BODY.n_1.1 ), 
    .\A[1].0 ( \errorDetect_RTL_BODY.n_2.0 ), 
    .\A[1].1 ( \errorDetect_RTL_BODY.n_2.1 ), 
    .\A[2].0 ( \errorDetect_RTL_BODY.n_3.0 ), 
    .\A[2].1 ( \errorDetect_RTL_BODY.n_3.1 ), 
    .\V[0] ( \pchb_cloud_0_inst_valid_out_0 ));
  \synthesis.qdi.logic2.LOGIC2_6.2 \errorDetect_RTL_BODY.g94 ( 
    .V ( \pchb_cloud_3_inst_valid_out_0 ), 
    .en ( \pchb_cloud_3_inst_en0 ), 
    .\A[0].0 ( \d[2].1 ), 
    .\A[0].1 ( \d[2].0 ), 
    .\A[1].0 ( \d[7].0 ), 
    .\A[1].1 ( \d[7].1 ), 
    .\X.0 ( \errorDetect_RTL_BODY.n_1.0 ), 
    .\X.1 ( \errorDetect_RTL_BODY.n_1.1 ));
  \synthesis.qdi.special.CTREE2.2 \ctreeerrorDetect_RTL_BODY.g94 ( 
    .x ( \pchb_cloud_3_inst_en0 ), 
    .\a[0] ( \pchb_cloud_3_inst_go ), 
    .\a[1] ( \c0.e ));
  \synthesis.qdi.special.CTRL21.2 \pchb_cloud_3_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_3_inst_go ), 
    .Ae ( \c3.e ), 
    .\A[0].0 ( \d[2].0 ), 
    .\A[0].1 ( \d[2].1 ), 
    .\A[1].0 ( \d[7].0 ), 
    .\A[1].1 ( \d[7].1 ), 
    .\V[0] ( \pchb_cloud_3_inst_valid_out_0 ));
  \synthesis.qdi.logic2.LOGIC2_6.2 \errorDetect_RTL_BODY.g95 ( 
    .V ( \pchb_cloud_4_inst_valid_out_0 ), 
    .en ( \pchb_cloud_4_inst_en0 ), 
    .\A[0].0 ( \d[4].1 ), 
    .\A[0].1 ( \d[4].0 ), 
    .\A[1].0 ( \d[6].0 ), 
    .\A[1].1 ( \d[6].1 ), 
    .\X.0 ( \errorDetect_RTL_BODY.n_0.0 ), 
    .\X.1 ( \errorDetect_RTL_BODY.n_0.1 ));
  \synthesis.qdi.special.CTREE2.2 \ctreeerrorDetect_RTL_BODY.g95 ( 
    .x ( \pchb_cloud_4_inst_en0 ), 
    .\a[0] ( \pchb_cloud_4_inst_go ), 
    .\a[1] ( \c24.e ));
  \synthesis.qdi.special.CTRL21.2 \pchb_cloud_4_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_4_inst_go ), 
    .Ae ( \c4.e ), 
    .\A[0].0 ( \d[4].0 ), 
    .\A[0].1 ( \d[4].1 ), 
    .\A[1].0 ( \d[6].0 ), 
    .\A[1].1 ( \d[6].1 ), 
    .\V[0] ( \pchb_cloud_4_inst_valid_out_0 ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_5_inst_In_RECEIVE.recv.bits[0].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In_d[0][0] ), 
    .\L.1 ( \In_d[1][0] ), 
    .\L.e ( \In_e[0] ), 
    .\R.0 ( \d[0].0 ), 
    .\R.1 ( \d[0].1 ), 
    .\R.e ( \pchb_cloud_5_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_5_inst_In_RECEIVE.recv.bits[0].recv_companion0 ( 
    .x ( \pchb_cloud_5_inst_en0 ), 
    .\a[0] ( \d[0]_15.e ), 
    .\a[1] ( \c24.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_6_inst_In_RECEIVE.recv.bits[1].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In_d[0][1] ), 
    .\L.1 ( \In_d[1][1] ), 
    .\L.e ( \In_e[1] ), 
    .\R.0 ( \d[1].0 ), 
    .\R.1 ( \d[1].1 ), 
    .\R.e ( \pchb_cloud_6_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_6_inst_In_RECEIVE.recv.bits[1].recv_companion0 ( 
    .x ( \pchb_cloud_6_inst_en0 ), 
    .\a[0] ( \d[1]_16.e ), 
    .\a[1] ( \c24.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_7_inst_In_RECEIVE.recv.bits[2].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In_d[0][2] ), 
    .\L.1 ( \In_d[1][2] ), 
    .\L.e ( \In_e[2] ), 
    .\R.0 ( \d[2].0 ), 
    .\R.1 ( \d[2].1 ), 
    .\R.e ( \pchb_cloud_7_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_7_inst_In_RECEIVE.recv.bits[2].recv_companion0 ( 
    .x ( \pchb_cloud_7_inst_en0 ), 
    .\a[0] ( \c3.e ), 
    .\a[1] ( \d[2]_17.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_8_inst_In_RECEIVE.recv.bits[3].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In_d[0][3] ), 
    .\L.1 ( \In_d[1][3] ), 
    .\L.e ( \In_e[3] ), 
    .\R.0 ( \d[3].0 ), 
    .\R.1 ( \d[3].1 ), 
    .\R.e ( \pchb_cloud_8_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_8_inst_In_RECEIVE.recv.bits[3].recv_companion0 ( 
    .x ( \pchb_cloud_8_inst_en0 ), 
    .\a[0] ( \d[3]_18.e ), 
    .\a[1] ( \c24.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_9_inst_In_RECEIVE.recv.bits[4].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In_d[0][4] ), 
    .\L.1 ( \In_d[1][4] ), 
    .\L.e ( \In_e[4] ), 
    .\R.0 ( \d[4].0 ), 
    .\R.1 ( \d[4].1 ), 
    .\R.e ( \pchb_cloud_9_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_9_inst_In_RECEIVE.recv.bits[4].recv_companion0 ( 
    .x ( \pchb_cloud_9_inst_en0 ), 
    .\a[0] ( \c4.e ), 
    .\a[1] ( \d[4]_19.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_10_inst_In_RECEIVE.recv.bits[5].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In_d[0][5] ), 
    .\L.1 ( \In_d[1][5] ), 
    .\L.e ( \In_e[5] ), 
    .\R.0 ( \d[5].0 ), 
    .\R.1 ( \d[5].1 ), 
    .\R.e ( \pchb_cloud_10_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_10_inst_In_RECEIVE.recv.bits[5].recv_companion0 ( 
    .x ( \pchb_cloud_10_inst_en0 ), 
    .\a[0] ( \d[5]_20.e ), 
    .\a[1] ( \c24.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_11_inst_In_RECEIVE.recv.bits[6].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In_d[0][6] ), 
    .\L.1 ( \In_d[1][6] ), 
    .\L.e ( \In_e[6] ), 
    .\R.0 ( \d[6].0 ), 
    .\R.1 ( \d[6].1 ), 
    .\R.e ( \pchb_cloud_11_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_11_inst_In_RECEIVE.recv.bits[6].recv_companion0 ( 
    .x ( \pchb_cloud_11_inst_en0 ), 
    .\a[0] ( \c4.e ), 
    .\a[1] ( \d[6]_21.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_12_inst_In_RECEIVE.recv.bits[7].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In_d[0][7] ), 
    .\L.1 ( \In_d[1][7] ), 
    .\L.e ( \In_e[7] ), 
    .\R.0 ( \d[7].0 ), 
    .\R.1 ( \d[7].1 ), 
    .\R.e ( \pchb_cloud_12_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_12_inst_In_RECEIVE.recv.bits[7].recv_companion0 ( 
    .x ( \pchb_cloud_12_inst_en0 ), 
    .\a[0] ( \c3.e ), 
    .\a[1] ( \d[7]_22.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_13_inst_In_RECEIVE.recv.bits[8].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In_d[0][8] ), 
    .\L.1 ( \In_d[1][8] ), 
    .\L.e ( \In_e[8] ), 
    .\R.0 ( \d[8].0 ), 
    .\R.1 ( \d[8].1 ), 
    .\R.e ( \pchb_cloud_13_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_13_inst_In_RECEIVE.recv.bits[8].recv_companion0 ( 
    .x ( \pchb_cloud_13_inst_en0 ), 
    .\a[0] ( \d[8]_23.e ), 
    .\a[1] ( \c24.e ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_14_inst_Error_SEND.send.bits[0].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Error_e ), 
    .\L.0 ( \n_36.0 ), 
    .\L.1 ( \n_36.1 ), 
    .\L.e ( \n_36.e ), 
    .\R.0 ( \Error_d[0][0] ), 
    .\R.1 ( \Error_d[1][0] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_15_inst_Out_SEND.send.bits[0].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[0] ), 
    .\L.0 ( \d[0].0 ), 
    .\L.1 ( \d[0].1 ), 
    .\L.e ( \d[0]_15.e ), 
    .\R.0 ( \Out_d[0][0] ), 
    .\R.1 ( \Out_d[1][0] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_16_inst_Out_SEND.send.bits[1].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[1] ), 
    .\L.0 ( \d[1].0 ), 
    .\L.1 ( \d[1].1 ), 
    .\L.e ( \d[1]_16.e ), 
    .\R.0 ( \Out_d[0][1] ), 
    .\R.1 ( \Out_d[1][1] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_17_inst_Out_SEND.send.bits[2].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[2] ), 
    .\L.0 ( \d[2].0 ), 
    .\L.1 ( \d[2].1 ), 
    .\L.e ( \d[2]_17.e ), 
    .\R.0 ( \Out_d[0][2] ), 
    .\R.1 ( \Out_d[1][2] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_18_inst_Out_SEND.send.bits[3].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[3] ), 
    .\L.0 ( \d[3].0 ), 
    .\L.1 ( \d[3].1 ), 
    .\L.e ( \d[3]_18.e ), 
    .\R.0 ( \Out_d[0][3] ), 
    .\R.1 ( \Out_d[1][3] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_19_inst_Out_SEND.send.bits[4].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[4] ), 
    .\L.0 ( \d[4].0 ), 
    .\L.1 ( \d[4].1 ), 
    .\L.e ( \d[4]_19.e ), 
    .\R.0 ( \Out_d[0][4] ), 
    .\R.1 ( \Out_d[1][4] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_20_inst_Out_SEND.send.bits[5].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[5] ), 
    .\L.0 ( \d[5].0 ), 
    .\L.1 ( \d[5].1 ), 
    .\L.e ( \d[5]_20.e ), 
    .\R.0 ( \Out_d[0][5] ), 
    .\R.1 ( \Out_d[1][5] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_21_inst_Out_SEND.send.bits[6].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[6] ), 
    .\L.0 ( \d[6].0 ), 
    .\L.1 ( \d[6].1 ), 
    .\L.e ( \d[6]_21.e ), 
    .\R.0 ( \Out_d[0][6] ), 
    .\R.1 ( \Out_d[1][6] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_22_inst_Out_SEND.send.bits[7].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[7] ), 
    .\L.0 ( \d[7].0 ), 
    .\L.1 ( \d[7].1 ), 
    .\L.e ( \d[7]_22.e ), 
    .\R.0 ( \Out_d[0][7] ), 
    .\R.1 ( \Out_d[1][7] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_23_inst_Out_SEND.send.bits[8].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[8] ), 
    .\L.0 ( \d[8].0 ), 
    .\L.1 ( \d[8].1 ), 
    .\L.e ( \d[8]_23.e ), 
    .\R.0 ( \Out_d[0][8] ), 
    .\R.1 ( \Out_d[1][8] ));
  \synthesis.qdi.logic3.LOGIC3_69.2 \errorDetect_RTL_BODY.g92 ( 
    .V ( \pchb_cloud_24_inst_valid_out_0 ), 
    .en ( \pchb_cloud_24_inst_en0 ), 
    .\A[0].0 ( \d[3].0 ), 
    .\A[0].1 ( \d[3].1 ), 
    .\A[1].0 ( \d[5].0 ), 
    .\A[1].1 ( \d[5].1 ), 
    .\A[2].0 ( \errorDetect_RTL_BODY.n_0.0 ), 
    .\A[2].1 ( \errorDetect_RTL_BODY.n_0.1 ), 
    .\X.0 ( \errorDetect_RTL_BODY.n_3.0 ), 
    .\X.1 ( \errorDetect_RTL_BODY.n_3.1 ));
  \synthesis.qdi.logic3.LOGIC3_69.2 \errorDetect_RTL_BODY.g93 ( 
    .V ( \pchb_cloud_24_inst_valid_out_1 ), 
    .en ( \pchb_cloud_24_inst_en0 ), 
    .\A[0].0 ( \d[1].1 ), 
    .\A[0].1 ( \d[1].0 ), 
    .\A[1].0 ( \d[0].0 ), 
    .\A[1].1 ( \d[0].1 ), 
    .\A[2].0 ( \d[8].0 ), 
    .\A[2].1 ( \d[8].1 ), 
    .\X.0 ( \errorDetect_RTL_BODY.n_2.0 ), 
    .\X.1 ( \errorDetect_RTL_BODY.n_2.1 ));
  \synthesis.qdi.special.CTRL62.2 \pchb_cloud_24_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_24_inst_go ), 
    .Ae ( \c24.e ), 
    .\A[0].0 ( \d[0].0 ), 
    .\A[0].1 ( \d[0].1 ), 
    .\A[1].0 ( \d[1].0 ), 
    .\A[1].1 ( \d[1].1 ), 
    .\A[2].0 ( \d[3].0 ), 
    .\A[2].1 ( \d[3].1 ), 
    .\A[3].0 ( \d[5].0 ), 
    .\A[3].1 ( \d[5].1 ), 
    .\A[4].0 ( \d[8].0 ), 
    .\A[4].1 ( \d[8].1 ), 
    .\A[5].0 ( \errorDetect_RTL_BODY.n_0.0 ), 
    .\A[5].1 ( \errorDetect_RTL_BODY.n_0.1 ), 
    .\V[0] ( \pchb_cloud_24_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_24_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreeerrorDetect_RTL_BODY.g92 ( 
    .\a[0] ( \pchb_cloud_24_inst_go ), 
    .\a[1] ( \c0.e ), 
    .\a[2] ( \c0.e ), 
    .x ( \pchb_cloud_24_inst_en0 ));

endmodule
