

// Generated by cosim_wrapper.pl to be used for cosim

module merge_cosim_wrapper(interface In0, interface In1, interface S, interface Out, input _RESET);

 merge merge_expanded (In0.e[0] , In0.e[1] , In0.e[2] , In0.e[3] , In0.e[4] , In0.e[5] 
 , In0.e[6] , In0.e[7] , In0.e[8] , In1.e[0] , In1.e[1] , In1.e[2] 
 , In1.e[3] , In1.e[4] , In1.e[5] , In1.e[6] , In1.e[7] , In1.e[8] 
 , Out.d[0][0] , Out.d[0][1] , Out.d[0][2] , Out.d[0][3] , Out.d[0][4] , Out.d[0][5] 
 , Out.d[0][6] , Out.d[0][7] , Out.d[0][8] , Out.d[1][0] , Out.d[1][1] , Out.d[1][2] 
 , Out.d[1][3] , Out.d[1][4] , Out.d[1][5] , Out.d[1][6] , Out.d[1][7] , Out.d[1][8] 
 , S.e[0] , In0.d[0][0] , In0.d[0][1] , In0.d[0][2] , In0.d[0][3] , In0.d[0][4] 
 , In0.d[0][5] , In0.d[0][6] , In0.d[0][7] , In0.d[0][8] , In0.d[1][0] , In0.d[1][1] 
 , In0.d[1][2] , In0.d[1][3] , In0.d[1][4] , In0.d[1][5] , In0.d[1][6] , In0.d[1][7] 
 , In0.d[1][8] , In1.d[0][0] , In1.d[0][1] , In1.d[0][2] , In1.d[0][3] , In1.d[0][4] 
 , In1.d[0][5] , In1.d[0][6] , In1.d[0][7] , In1.d[0][8] , In1.d[1][0] , In1.d[1][1] 
 , In1.d[1][2] , In1.d[1][3] , In1.d[1][4] , In1.d[1][5] , In1.d[1][6] , In1.d[1][7] 
 , In1.d[1][8] , Out.e[0] , Out.e[1] , Out.e[2] , Out.e[3] , Out.e[4] 
 , Out.e[5] , Out.e[6] , Out.e[7] , Out.e[8] , S.d[0][0] , S.d[1][0] 
 , _RESET );

endmodule

// Generated by E-GRAPH (EGS) v0.01

module merge (\In0_e[0] , \In0_e[1] , \In0_e[2] , \In0_e[3] , \In0_e[4] , \In0_e[5] , \In0_e[6] , \In0_e[7] , \In0_e[8] , 
  \In1_e[0] , \In1_e[1] , \In1_e[2] , \In1_e[3] , \In1_e[4] , \In1_e[5] , \In1_e[6] , \In1_e[7] , \In1_e[8] , \Out_d[0][0] , 
  \Out_d[0][1] , \Out_d[0][2] , \Out_d[0][3] , \Out_d[0][4] , \Out_d[0][5] , \Out_d[0][6] , \Out_d[0][7] , \Out_d[0][8] , 
  \Out_d[1][0] , \Out_d[1][1] , \Out_d[1][2] , \Out_d[1][3] , \Out_d[1][4] , \Out_d[1][5] , \Out_d[1][6] , \Out_d[1][7] , 
  \Out_d[1][8] , \S_e , \In0_d[0][0] , \In0_d[0][1] , \In0_d[0][2] , \In0_d[0][3] , \In0_d[0][4] , \In0_d[0][5] , \In0_d[0][6] , 
  \In0_d[0][7] , \In0_d[0][8] , \In0_d[1][0] , \In0_d[1][1] , \In0_d[1][2] , \In0_d[1][3] , \In0_d[1][4] , \In0_d[1][5] , 
  \In0_d[1][6] , \In0_d[1][7] , \In0_d[1][8] , \In1_d[0][0] , \In1_d[0][1] , \In1_d[0][2] , \In1_d[0][3] , \In1_d[0][4] , 
  \In1_d[0][5] , \In1_d[0][6] , \In1_d[0][7] , \In1_d[0][8] , \In1_d[1][0] , \In1_d[1][1] , \In1_d[1][2] , \In1_d[1][3] , 
  \In1_d[1][4] , \In1_d[1][5] , \In1_d[1][6] , \In1_d[1][7] , \In1_d[1][8] , \Out_e[0] , \Out_e[1] , \Out_e[2] , \Out_e[3] , 
  \Out_e[4] , \Out_e[5] , \Out_e[6] , \Out_e[7] , \Out_e[8] , \S_d[0][0] , \S_d[1][0] , _RESET );
  input  \In0_d[0][0] , \In0_d[0][1] , \In0_d[0][2] , \In0_d[0][3] , \In0_d[0][4] , \In0_d[0][5] , \In0_d[0][6] , \In0_d[0][7] ;
  input  \In0_d[0][8] , \In0_d[1][0] , \In0_d[1][1] , \In0_d[1][2] , \In0_d[1][3] , \In0_d[1][4] , \In0_d[1][5] , \In0_d[1][6] ;
  input  \In0_d[1][7] , \In0_d[1][8] , \In1_d[0][0] , \In1_d[0][1] , \In1_d[0][2] , \In1_d[0][3] , \In1_d[0][4] , \In1_d[0][5] ;
  input  \In1_d[0][6] , \In1_d[0][7] , \In1_d[0][8] , \In1_d[1][0] , \In1_d[1][1] , \In1_d[1][2] , \In1_d[1][3] , \In1_d[1][4] ;
  input  \In1_d[1][5] , \In1_d[1][6] , \In1_d[1][7] , \In1_d[1][8] , \Out_e[0] , \Out_e[1] , \Out_e[2] , \Out_e[3] , \Out_e[4] ;
  input  \Out_e[5] , \Out_e[6] , \Out_e[7] , \Out_e[8] , \S_d[0][0] , \S_d[1][0] , _RESET ;

  output \In0_e[0] , \In0_e[1] , \In0_e[2] , \In0_e[3] , \In0_e[4] , \In0_e[5] , \In0_e[6] , \In0_e[7] , \In0_e[8] , \In1_e[0] ;
  output \In1_e[1] , \In1_e[2] , \In1_e[3] , \In1_e[4] , \In1_e[5] , \In1_e[6] , \In1_e[7] , \In1_e[8] , \Out_d[0][0] ;
  output \Out_d[0][1] , \Out_d[0][2] , \Out_d[0][3] , \Out_d[0][4] , \Out_d[0][5] , \Out_d[0][6] , \Out_d[0][7] , \Out_d[0][8] ;
  output \Out_d[1][0] , \Out_d[1][1] , \Out_d[1][2] , \Out_d[1][3] , \Out_d[1][4] , \Out_d[1][5] , \Out_d[1][6] , \Out_d[1][7] ;
  output \Out_d[1][8] , \S_e ;

  wire   \In0_e[0] , \In0_e[1] , \In0_e[2] , \In0_e[3] , \In0_e[4] , \In0_e[5] , \In0_e[6] , \In0_e[7] , \In0_e[8] , \In1_e[0] ;
  wire   \In1_e[1] , \In1_e[2] , \In1_e[3] , \In1_e[4] , \In1_e[5] , \In1_e[6] , \In1_e[7] , \In1_e[8] , \Out_d[0][0] ;
  wire   \Out_d[0][1] , \Out_d[0][2] , \Out_d[0][3] , \Out_d[0][4] , \Out_d[0][5] , \Out_d[0][6] , \Out_d[0][7] , \Out_d[0][8] ;
  wire   \Out_d[1][0] , \Out_d[1][1] , \Out_d[1][2] , \Out_d[1][3] , \Out_d[1][4] , \Out_d[1][5] , \Out_d[1][6] , \Out_d[1][7] ;
  wire   \Out_d[1][8] , \S_e , \c19.e , \c20.e , \c21.e , \c22.e , \c23.e , \c24.e , \c25.e , \c26.e , \c27.e , \c28.e , \c29.e ;
  wire   \c30.e , \c31.e , \c32.e , \c33.e , \c34.e , \c35.e , \c36.e , \d[0].0 , \d[0].1 , \d[1].0 , \d[1].1 , \d[2].0 ;
  wire   \d[2].1 , \d[3].0 , \d[3].1 , \d[4].0 , \d[4].1 , \d[5].0 , \d[5].1 , \d[6].0 , \d[6].1 , \d[7].0 , \d[7].1 , \d[8].0 ;
  wire   \d[8].1 , \n_27.0 , \n_27.1 , \n_28.0 , \n_28.1 , \n_29.0 , \n_29.1 , \n_30.0 , \n_30.1 , \n_31.0 , \n_31.1 , \n_32.0 ;
  wire   \n_32.1 , \n_33.0 , \n_33.1 , \n_34.0 , \n_34.1 , \n_35.0 , \n_35.1 , \n_36.0 , \n_36.1 , \n_36_41.e , \n_36_42.e ;
  wire   \n_36_43.e , \n_36_44.e , \n_36_FX0.0 , \n_36_FX0.1 , \n_36_FX1.0 , \n_36_FX1.1 , \n_36_FX1_45.e ;
  wire   \n_36_FX1_SX0_iter2.0 , \n_36_FX1_SX0_iter2.1 , \n_36_FX2_a.0 , \n_36_FX2_a.1 , \n_36_FX2_b.0 , \n_36_FX2_b.1 ;
  wire   \n_36_FX3_a.0 , \n_36_FX3_a.1 , \n_36_FX3_b.0 , \n_36_FX3_b.1 , \n_48.0 , \n_48.1 , \n_48.e , \n_49.0 , \n_49.1 ;
  wire   \n_49.e , \n_50.0 , \n_50.1 , \n_50.e , \n_51.0 , \n_51.1 , \n_51.e , \n_52.0 , \n_52.1 , \n_52.e , \n_53.0 , \n_53.1 ;
  wire   \n_53.e , \n_54.0 , \n_54.1 , \n_54.e , \n_55.0 , \n_55.1 , \n_55.e , \n_56.0 , \n_56.1 , \n_56.e ;
  wire   \pchb_cfbuf_43_FX_inst_n_36_0e , \pchb_cfbuf_43_FX_inst_n_36_1e , \pchb_cfbuf_44_FX_inst_n_36_0e ;
  wire   \pchb_cfbuf_44_FX_inst_n_36_1e , \pchb_cloud_17_inst_go , \pchb_cloud_17_inst_valid_out_0 , \pchb_cloud_37_inst_go ;
  wire   \pchb_cloud_37_inst_valid_out_0 , \pchb_cloud_37_inst_valid_out_1 , \pchb_cloud_38_inst_go ;
  wire   \pchb_cloud_38_inst_valid_out_0 , \pchb_cloud_38_inst_valid_out_1 , \pchb_cloud_39_inst_go ;
  wire   \pchb_cloud_39_inst_valid_out_0 , \pchb_cloud_39_inst_valid_out_1 , \pchb_cloud_40_inst_go ;
  wire   \pchb_cloud_40_inst_valid_out_0 , \pchb_cloud_40_inst_valid_out_1 ;

  trireg \c17.e , \c37.e , \c38.e , \c39.e , \c40.e , \pchb_cfbuf_41_FX_inst_en0 , \pchb_cfbuf_42_FX_inst_en0 ;
  trireg \pchb_cfbuf_43_FX_inst_en0 , \pchb_cfbuf_43_FX_inst_en1 , \pchb_cfbuf_44_FX_inst_en0 , \pchb_cfbuf_44_FX_inst_en1 ;
  trireg \pchb_cloud_17_inst_en0 , \pchb_cloud_18_inst_en0 , \pchb_cloud_37_inst_en0 , \pchb_cloud_38_inst_en0 ;
  trireg \pchb_cloud_39_inst_en0 , \pchb_cloud_40_inst_en0 ;



  \synthesis.qdi.special.BUF.2 \pchb_cloud_0_inst_Out_SEND.send.bits[0].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[0] ), 
    .\L.0 ( \n_56.0 ), 
    .\L.1 ( \n_56.1 ), 
    .\L.e ( \n_56.e ), 
    .\R.0 ( \Out_d[0][0] ), 
    .\R.1 ( \Out_d[1][0] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_1_inst_Out_SEND.send.bits[1].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[1] ), 
    .\L.0 ( \n_55.0 ), 
    .\L.1 ( \n_55.1 ), 
    .\L.e ( \n_55.e ), 
    .\R.0 ( \Out_d[0][1] ), 
    .\R.1 ( \Out_d[1][1] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_2_inst_Out_SEND.send.bits[2].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[2] ), 
    .\L.0 ( \n_54.0 ), 
    .\L.1 ( \n_54.1 ), 
    .\L.e ( \n_54.e ), 
    .\R.0 ( \Out_d[0][2] ), 
    .\R.1 ( \Out_d[1][2] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_3_inst_Out_SEND.send.bits[3].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[3] ), 
    .\L.0 ( \n_53.0 ), 
    .\L.1 ( \n_53.1 ), 
    .\L.e ( \n_53.e ), 
    .\R.0 ( \Out_d[0][3] ), 
    .\R.1 ( \Out_d[1][3] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_4_inst_Out_SEND.send.bits[4].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[4] ), 
    .\L.0 ( \n_52.0 ), 
    .\L.1 ( \n_52.1 ), 
    .\L.e ( \n_52.e ), 
    .\R.0 ( \Out_d[0][4] ), 
    .\R.1 ( \Out_d[1][4] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_5_inst_Out_SEND.send.bits[5].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[5] ), 
    .\L.0 ( \n_51.0 ), 
    .\L.1 ( \n_51.1 ), 
    .\L.e ( \n_51.e ), 
    .\R.0 ( \Out_d[0][5] ), 
    .\R.1 ( \Out_d[1][5] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_6_inst_Out_SEND.send.bits[6].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[6] ), 
    .\L.0 ( \n_50.0 ), 
    .\L.1 ( \n_50.1 ), 
    .\L.e ( \n_50.e ), 
    .\R.0 ( \Out_d[0][6] ), 
    .\R.1 ( \Out_d[1][6] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_7_inst_Out_SEND.send.bits[7].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[7] ), 
    .\L.0 ( \n_49.0 ), 
    .\L.1 ( \n_49.1 ), 
    .\L.e ( \n_49.e ), 
    .\R.0 ( \Out_d[0][7] ), 
    .\R.1 ( \Out_d[1][7] ));
  \synthesis.qdi.special.BUF.2 \pchb_cloud_8_inst_Out_SEND.send.bits[8].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out_e[8] ), 
    .\L.0 ( \n_48.0 ), 
    .\L.1 ( \n_48.1 ), 
    .\L.e ( \n_48.e ), 
    .\R.0 ( \Out_d[0][8] ), 
    .\R.1 ( \Out_d[1][8] ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \merge_RTL_BODY.g173 ( 
    .V ( \pchb_cloud_17_inst_valid_out_0 ), 
    .en ( \pchb_cloud_17_inst_en0 ), 
    .\A[0].0 ( \d[3].1 ), 
    .\A[0].1 ( \d[3].0 ), 
    .\A[1].0 ( \n_32.1 ), 
    .\A[1].1 ( \n_32.0 ), 
    .\A[2].0 ( \n_36_FX1_SX0_iter2.1 ), 
    .\A[2].1 ( \n_36_FX1_SX0_iter2.0 ), 
    .\A[3].0 ( \n_36_FX1_SX0_iter2.0 ), 
    .\A[3].1 ( \n_36_FX1_SX0_iter2.1 ), 
    .\X.0 ( \n_53.0 ), 
    .\X.1 ( \n_53.1 ));
  \synthesis.qdi.special.CTREE2.2 \ctreemerge_RTL_BODY.g173 ( 
    .x ( \pchb_cloud_17_inst_en0 ), 
    .\a[0] ( \pchb_cloud_17_inst_go ), 
    .\a[1] ( \n_53.e ));
  \synthesis.qdi.special.CTRL31.2 \pchb_cloud_17_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_17_inst_go ), 
    .Ae ( \c17.e ), 
    .\A[0].0 ( \d[3].0 ), 
    .\A[0].1 ( \d[3].1 ), 
    .\A[1].0 ( \n_32.0 ), 
    .\A[1].1 ( \n_32.1 ), 
    .\A[2].0 ( \n_36_FX1_SX0_iter2.0 ), 
    .\A[2].1 ( \n_36_FX1_SX0_iter2.1 ), 
    .\V[0] ( \pchb_cloud_17_inst_valid_out_0 ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_18_inst_S_RECEIVE.recv.bits[0].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \S_d[0][0] ), 
    .\L.1 ( \S_d[1][0] ), 
    .\L.e ( \S_e ), 
    .\R.0 ( \n_36.0 ), 
    .\R.1 ( \n_36.1 ), 
    .\R.e ( \pchb_cloud_18_inst_en0 ));
  \synthesis.qdi.special.CTREE4.2 \pchb_cloud_18_inst_S_RECEIVE.recv.bits[0].recv_companion0 ( 
    .x ( \pchb_cloud_18_inst_en0 ), 
    .\a[0] ( \n_36_41.e ), 
    .\a[1] ( \n_36_42.e ), 
    .\a[2] ( \n_36_43.e ), 
    .\a[3] ( \n_36_44.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_19_inst_In0_RECEIVE.recv.bits[0].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In0_d[0][0] ), 
    .\L.1 ( \In0_d[1][0] ), 
    .\E.1 ( \n_36_FX3_b.0 ), 
    .\E.0 ( \n_36_FX3_b.1 ), 
    .\E.e ( \c19.e ), 
    .\L.e ( \In0_e[0] ), 
    .\R[0].0 ( \d[0].0 ), 
    .\R[0].1 ( \d[0].1 ), 
    .\R[0].e ( \c40.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_20_inst_In0_RECEIVE.recv.bits[1].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In0_d[0][1] ), 
    .\L.1 ( \In0_d[1][1] ), 
    .\E.1 ( \n_36_FX3_b.0 ), 
    .\E.0 ( \n_36_FX3_b.1 ), 
    .\E.e ( \c20.e ), 
    .\L.e ( \In0_e[1] ), 
    .\R[0].0 ( \d[1].0 ), 
    .\R[0].1 ( \d[1].1 ), 
    .\R[0].e ( \c39.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_21_inst_In0_RECEIVE.recv.bits[2].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In0_d[0][2] ), 
    .\L.1 ( \In0_d[1][2] ), 
    .\E.1 ( \n_36_FX3_b.0 ), 
    .\E.0 ( \n_36_FX3_b.1 ), 
    .\E.e ( \c21.e ), 
    .\L.e ( \In0_e[2] ), 
    .\R[0].0 ( \d[2].0 ), 
    .\R[0].1 ( \d[2].1 ), 
    .\R[0].e ( \c38.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_22_inst_In0_RECEIVE.recv.bits[3].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In0_d[0][3] ), 
    .\L.1 ( \In0_d[1][3] ), 
    .\E.1 ( \n_36_FX3_b.0 ), 
    .\E.0 ( \n_36_FX3_b.1 ), 
    .\E.e ( \c22.e ), 
    .\L.e ( \In0_e[3] ), 
    .\R[0].0 ( \d[3].0 ), 
    .\R[0].1 ( \d[3].1 ), 
    .\R[0].e ( \c17.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_23_inst_In0_RECEIVE.recv.bits[4].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In0_d[0][4] ), 
    .\L.1 ( \In0_d[1][4] ), 
    .\E.1 ( \n_36_FX3_a.0 ), 
    .\E.0 ( \n_36_FX3_a.1 ), 
    .\E.e ( \c23.e ), 
    .\L.e ( \In0_e[4] ), 
    .\R[0].0 ( \d[4].0 ), 
    .\R[0].1 ( \d[4].1 ), 
    .\R[0].e ( \c39.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_24_inst_In0_RECEIVE.recv.bits[5].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In0_d[0][5] ), 
    .\L.1 ( \In0_d[1][5] ), 
    .\E.1 ( \n_36_FX3_a.0 ), 
    .\E.0 ( \n_36_FX3_a.1 ), 
    .\E.e ( \c24.e ), 
    .\L.e ( \In0_e[5] ), 
    .\R[0].0 ( \d[5].0 ), 
    .\R[0].1 ( \d[5].1 ), 
    .\R[0].e ( \c38.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_25_inst_In0_RECEIVE.recv.bits[6].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In0_d[0][6] ), 
    .\L.1 ( \In0_d[1][6] ), 
    .\E.1 ( \n_36_FX3_a.0 ), 
    .\E.0 ( \n_36_FX3_a.1 ), 
    .\E.e ( \c25.e ), 
    .\L.e ( \In0_e[6] ), 
    .\R[0].0 ( \d[6].0 ), 
    .\R[0].1 ( \d[6].1 ), 
    .\R[0].e ( \c40.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_26_inst_In0_RECEIVE.recv.bits[7].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In0_d[0][7] ), 
    .\L.1 ( \In0_d[1][7] ), 
    .\E.1 ( \n_36_FX2_b.0 ), 
    .\E.0 ( \n_36_FX2_b.1 ), 
    .\E.e ( \c26.e ), 
    .\L.e ( \In0_e[7] ), 
    .\R[0].0 ( \d[7].0 ), 
    .\R[0].1 ( \d[7].1 ), 
    .\R[0].e ( \c37.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_27_inst_In0_RECEIVE.recv.bits[8].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In0_d[0][8] ), 
    .\L.1 ( \In0_d[1][8] ), 
    .\E.1 ( \n_36_FX2_b.0 ), 
    .\E.0 ( \n_36_FX2_b.1 ), 
    .\E.e ( \c27.e ), 
    .\L.e ( \In0_e[8] ), 
    .\R[0].0 ( \d[8].0 ), 
    .\R[0].1 ( \d[8].1 ), 
    .\R[0].e ( \c37.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_28_inst_In1_RECEIVE.recv.bits[0].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In1_d[0][0] ), 
    .\L.1 ( \In1_d[1][0] ), 
    .\E.0 ( \n_36_FX2_b.0 ), 
    .\E.1 ( \n_36_FX2_b.1 ), 
    .\E.e ( \c28.e ), 
    .\L.e ( \In1_e[0] ), 
    .\R[0].0 ( \n_35.0 ), 
    .\R[0].1 ( \n_35.1 ), 
    .\R[0].e ( \c40.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_29_inst_In1_RECEIVE.recv.bits[1].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In1_d[0][1] ), 
    .\L.1 ( \In1_d[1][1] ), 
    .\E.0 ( \n_36_FX2_b.0 ), 
    .\E.1 ( \n_36_FX2_b.1 ), 
    .\E.e ( \c29.e ), 
    .\L.e ( \In1_e[1] ), 
    .\R[0].0 ( \n_34.0 ), 
    .\R[0].1 ( \n_34.1 ), 
    .\R[0].e ( \c39.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_30_inst_In1_RECEIVE.recv.bits[2].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In1_d[0][2] ), 
    .\L.1 ( \In1_d[1][2] ), 
    .\E.0 ( \n_36_FX2_a.0 ), 
    .\E.1 ( \n_36_FX2_a.1 ), 
    .\E.e ( \c30.e ), 
    .\L.e ( \In1_e[2] ), 
    .\R[0].0 ( \n_33.0 ), 
    .\R[0].1 ( \n_33.1 ), 
    .\R[0].e ( \c38.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_31_inst_In1_RECEIVE.recv.bits[3].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In1_d[0][3] ), 
    .\L.1 ( \In1_d[1][3] ), 
    .\E.0 ( \n_36_FX2_a.0 ), 
    .\E.1 ( \n_36_FX2_a.1 ), 
    .\E.e ( \c31.e ), 
    .\L.e ( \In1_e[3] ), 
    .\R[0].0 ( \n_32.0 ), 
    .\R[0].1 ( \n_32.1 ), 
    .\R[0].e ( \c17.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_32_inst_In1_RECEIVE.recv.bits[4].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In1_d[0][4] ), 
    .\L.1 ( \In1_d[1][4] ), 
    .\E.0 ( \n_36_FX2_a.0 ), 
    .\E.1 ( \n_36_FX2_a.1 ), 
    .\E.e ( \c32.e ), 
    .\L.e ( \In1_e[4] ), 
    .\R[0].0 ( \n_31.0 ), 
    .\R[0].1 ( \n_31.1 ), 
    .\R[0].e ( \c39.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_33_inst_In1_RECEIVE.recv.bits[5].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In1_d[0][5] ), 
    .\L.1 ( \In1_d[1][5] ), 
    .\E.0 ( \n_36_FX2_a.0 ), 
    .\E.1 ( \n_36_FX2_a.1 ), 
    .\E.e ( \c33.e ), 
    .\L.e ( \In1_e[5] ), 
    .\R[0].0 ( \n_30.0 ), 
    .\R[0].1 ( \n_30.1 ), 
    .\R[0].e ( \c38.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_34_inst_In1_RECEIVE.recv.bits[6].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In1_d[0][6] ), 
    .\L.1 ( \In1_d[1][6] ), 
    .\E.0 ( \n_36_FX1.0 ), 
    .\E.1 ( \n_36_FX1.1 ), 
    .\E.e ( \c34.e ), 
    .\L.e ( \In1_e[6] ), 
    .\R[0].0 ( \n_29.0 ), 
    .\R[0].1 ( \n_29.1 ), 
    .\R[0].e ( \c40.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_35_inst_In1_RECEIVE.recv.bits[7].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In1_d[0][7] ), 
    .\L.1 ( \In1_d[1][7] ), 
    .\E.0 ( \n_36_FX1.0 ), 
    .\E.1 ( \n_36_FX1.1 ), 
    .\E.e ( \c35.e ), 
    .\L.e ( \In1_e[7] ), 
    .\R[0].0 ( \n_28.0 ), 
    .\R[0].1 ( \n_28.1 ), 
    .\R[0].e ( \c37.e ));
  \synthesis.qdi.special.RECV_1of2.2 \pchb_cloud_36_inst_In1_RECEIVE.recv.bits[8].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In1_d[0][8] ), 
    .\L.1 ( \In1_d[1][8] ), 
    .\E.0 ( \n_36_FX1.0 ), 
    .\E.1 ( \n_36_FX1.1 ), 
    .\E.e ( \c36.e ), 
    .\L.e ( \In1_e[8] ), 
    .\R[0].0 ( \n_27.0 ), 
    .\R[0].1 ( \n_27.1 ), 
    .\R[0].e ( \c37.e ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \merge_RTL_BODY.g165 ( 
    .V ( \pchb_cloud_37_inst_valid_out_0 ), 
    .en ( \pchb_cloud_37_inst_en0 ), 
    .\A[0].0 ( \d[8].1 ), 
    .\A[0].1 ( \d[8].0 ), 
    .\A[1].0 ( \n_27.1 ), 
    .\A[1].1 ( \n_27.0 ), 
    .\A[2].0 ( \n_36_FX0.1 ), 
    .\A[2].1 ( \n_36_FX0.0 ), 
    .\A[3].0 ( \n_36_FX0.0 ), 
    .\A[3].1 ( \n_36_FX0.1 ), 
    .\X.0 ( \n_48.0 ), 
    .\X.1 ( \n_48.1 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \merge_RTL_BODY.g166 ( 
    .V ( \pchb_cloud_37_inst_valid_out_1 ), 
    .en ( \pchb_cloud_37_inst_en0 ), 
    .\A[0].0 ( \d[7].1 ), 
    .\A[0].1 ( \d[7].0 ), 
    .\A[1].0 ( \n_28.1 ), 
    .\A[1].1 ( \n_28.0 ), 
    .\A[2].0 ( \n_36_FX0.1 ), 
    .\A[2].1 ( \n_36_FX0.0 ), 
    .\A[3].0 ( \n_36_FX0.0 ), 
    .\A[3].1 ( \n_36_FX0.1 ), 
    .\X.0 ( \n_49.0 ), 
    .\X.1 ( \n_49.1 ));
  \synthesis.qdi.special.CTRL52.2 \pchb_cloud_37_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_37_inst_go ), 
    .Ae ( \c37.e ), 
    .\A[0].0 ( \d[7].0 ), 
    .\A[0].1 ( \d[7].1 ), 
    .\A[1].0 ( \d[8].0 ), 
    .\A[1].1 ( \d[8].1 ), 
    .\A[2].0 ( \n_27.0 ), 
    .\A[2].1 ( \n_27.1 ), 
    .\A[3].0 ( \n_28.0 ), 
    .\A[3].1 ( \n_28.1 ), 
    .\A[4].0 ( \n_36_FX0.0 ), 
    .\A[4].1 ( \n_36_FX0.1 ), 
    .\V[0] ( \pchb_cloud_37_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_37_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreemerge_RTL_BODY.g165 ( 
    .\a[0] ( \pchb_cloud_37_inst_go ), 
    .\a[1] ( \n_48.e ), 
    .\a[2] ( \n_49.e ), 
    .x ( \pchb_cloud_37_inst_en0 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \merge_RTL_BODY.g167 ( 
    .V ( \pchb_cloud_38_inst_valid_out_0 ), 
    .en ( \pchb_cloud_38_inst_en0 ), 
    .\A[0].0 ( \d[5].1 ), 
    .\A[0].1 ( \d[5].0 ), 
    .\A[1].0 ( \n_30.1 ), 
    .\A[1].1 ( \n_30.0 ), 
    .\A[2].0 ( \n_36_FX0.1 ), 
    .\A[2].1 ( \n_36_FX0.0 ), 
    .\A[3].0 ( \n_36_FX0.0 ), 
    .\A[3].1 ( \n_36_FX0.1 ), 
    .\X.0 ( \n_51.0 ), 
    .\X.1 ( \n_51.1 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \merge_RTL_BODY.g168 ( 
    .V ( \pchb_cloud_38_inst_valid_out_1 ), 
    .en ( \pchb_cloud_38_inst_en0 ), 
    .\A[0].0 ( \d[2].1 ), 
    .\A[0].1 ( \d[2].0 ), 
    .\A[1].0 ( \n_33.1 ), 
    .\A[1].1 ( \n_33.0 ), 
    .\A[2].0 ( \n_36_FX0.1 ), 
    .\A[2].1 ( \n_36_FX0.0 ), 
    .\A[3].0 ( \n_36_FX0.0 ), 
    .\A[3].1 ( \n_36_FX0.1 ), 
    .\X.0 ( \n_54.0 ), 
    .\X.1 ( \n_54.1 ));
  \synthesis.qdi.special.CTRL52.2 \pchb_cloud_38_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_38_inst_go ), 
    .Ae ( \c38.e ), 
    .\A[0].0 ( \d[2].0 ), 
    .\A[0].1 ( \d[2].1 ), 
    .\A[1].0 ( \d[5].0 ), 
    .\A[1].1 ( \d[5].1 ), 
    .\A[2].0 ( \n_30.0 ), 
    .\A[2].1 ( \n_30.1 ), 
    .\A[3].0 ( \n_33.0 ), 
    .\A[3].1 ( \n_33.1 ), 
    .\A[4].0 ( \n_36_FX0.0 ), 
    .\A[4].1 ( \n_36_FX0.1 ), 
    .\V[0] ( \pchb_cloud_38_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_38_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreemerge_RTL_BODY.g167 ( 
    .\a[0] ( \pchb_cloud_38_inst_go ), 
    .\a[1] ( \n_51.e ), 
    .\a[2] ( \n_54.e ), 
    .x ( \pchb_cloud_38_inst_en0 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \merge_RTL_BODY.g169 ( 
    .V ( \pchb_cloud_39_inst_valid_out_0 ), 
    .en ( \pchb_cloud_39_inst_en0 ), 
    .\A[0].0 ( \d[1].1 ), 
    .\A[0].1 ( \d[1].0 ), 
    .\A[1].0 ( \n_34.1 ), 
    .\A[1].1 ( \n_34.0 ), 
    .\A[2].0 ( \n_36_FX0.1 ), 
    .\A[2].1 ( \n_36_FX0.0 ), 
    .\A[3].0 ( \n_36_FX0.0 ), 
    .\A[3].1 ( \n_36_FX0.1 ), 
    .\X.0 ( \n_55.0 ), 
    .\X.1 ( \n_55.1 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \merge_RTL_BODY.g170 ( 
    .V ( \pchb_cloud_39_inst_valid_out_1 ), 
    .en ( \pchb_cloud_39_inst_en0 ), 
    .\A[0].0 ( \d[4].1 ), 
    .\A[0].1 ( \d[4].0 ), 
    .\A[1].0 ( \n_31.1 ), 
    .\A[1].1 ( \n_31.0 ), 
    .\A[2].0 ( \n_36_FX0.1 ), 
    .\A[2].1 ( \n_36_FX0.0 ), 
    .\A[3].0 ( \n_36_FX0.0 ), 
    .\A[3].1 ( \n_36_FX0.1 ), 
    .\X.0 ( \n_52.0 ), 
    .\X.1 ( \n_52.1 ));
  \synthesis.qdi.special.CTRL52.2 \pchb_cloud_39_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_39_inst_go ), 
    .Ae ( \c39.e ), 
    .\A[0].0 ( \d[1].0 ), 
    .\A[0].1 ( \d[1].1 ), 
    .\A[1].0 ( \d[4].0 ), 
    .\A[1].1 ( \d[4].1 ), 
    .\A[2].0 ( \n_31.0 ), 
    .\A[2].1 ( \n_31.1 ), 
    .\A[3].0 ( \n_34.0 ), 
    .\A[3].1 ( \n_34.1 ), 
    .\A[4].0 ( \n_36_FX0.0 ), 
    .\A[4].1 ( \n_36_FX0.1 ), 
    .\V[0] ( \pchb_cloud_39_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_39_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreemerge_RTL_BODY.g169 ( 
    .\a[0] ( \pchb_cloud_39_inst_go ), 
    .\a[1] ( \n_52.e ), 
    .\a[2] ( \n_55.e ), 
    .x ( \pchb_cloud_39_inst_en0 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \merge_RTL_BODY.g171 ( 
    .V ( \pchb_cloud_40_inst_valid_out_0 ), 
    .en ( \pchb_cloud_40_inst_en0 ), 
    .\A[0].0 ( \d[0].1 ), 
    .\A[0].1 ( \d[0].0 ), 
    .\A[1].0 ( \n_35.1 ), 
    .\A[1].1 ( \n_35.0 ), 
    .\A[2].0 ( \n_36_FX0.1 ), 
    .\A[2].1 ( \n_36_FX0.0 ), 
    .\A[3].0 ( \n_36_FX0.0 ), 
    .\A[3].1 ( \n_36_FX0.1 ), 
    .\X.0 ( \n_56.0 ), 
    .\X.1 ( \n_56.1 ));
  \synthesis.qdi.logic4.LOGIC4_0357.2 \merge_RTL_BODY.g172 ( 
    .V ( \pchb_cloud_40_inst_valid_out_1 ), 
    .en ( \pchb_cloud_40_inst_en0 ), 
    .\A[0].0 ( \d[6].1 ), 
    .\A[0].1 ( \d[6].0 ), 
    .\A[1].0 ( \n_29.1 ), 
    .\A[1].1 ( \n_29.0 ), 
    .\A[2].0 ( \n_36_FX0.1 ), 
    .\A[2].1 ( \n_36_FX0.0 ), 
    .\A[3].0 ( \n_36_FX0.0 ), 
    .\A[3].1 ( \n_36_FX0.1 ), 
    .\X.0 ( \n_50.0 ), 
    .\X.1 ( \n_50.1 ));
  \synthesis.qdi.special.CTRL52.2 \pchb_cloud_40_inst_controller ( 
    ._RESET ( _RESET ), 
    .en ( \pchb_cloud_40_inst_go ), 
    .Ae ( \c40.e ), 
    .\A[0].0 ( \d[0].0 ), 
    .\A[0].1 ( \d[0].1 ), 
    .\A[1].0 ( \d[6].0 ), 
    .\A[1].1 ( \d[6].1 ), 
    .\A[2].0 ( \n_29.0 ), 
    .\A[2].1 ( \n_29.1 ), 
    .\A[3].0 ( \n_35.0 ), 
    .\A[3].1 ( \n_35.1 ), 
    .\A[4].0 ( \n_36_FX0.0 ), 
    .\A[4].1 ( \n_36_FX0.1 ), 
    .\V[0] ( \pchb_cloud_40_inst_valid_out_0 ), 
    .\V[1] ( \pchb_cloud_40_inst_valid_out_1 ));
  \synthesis.qdi.special.CTREE3.2 \ctreemerge_RTL_BODY.g171 ( 
    .\a[0] ( \pchb_cloud_40_inst_go ), 
    .\a[1] ( \n_50.e ), 
    .\a[2] ( \n_56.e ), 
    .x ( \pchb_cloud_40_inst_en0 ));
  \synthesis.qdi.special.BUF.6 \pchb_cfbuf_41_FX_inst_n_36_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \n_36.0 ), 
    .\L.1 ( \n_36.1 ), 
    .\L.e ( \n_36_41.e ), 
    .\R.0 ( \n_36_FX0.0 ), 
    .\R.1 ( \n_36_FX0.1 ), 
    .\R.e ( \pchb_cfbuf_41_FX_inst_en0 ));
  \synthesis.qdi.special.CTREE4.2 \pchb_cfbuf_41_FX_inst_n_36_buf_companion0 ( 
    .x ( \pchb_cfbuf_41_FX_inst_en0 ), 
    .\a[0] ( \c40.e ), 
    .\a[1] ( \c39.e ), 
    .\a[2] ( \c38.e ), 
    .\a[3] ( \c37.e ));
  \synthesis.qdi.special.BUF.4 \pchb_cfbuf_42_FX_inst_n_36_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \n_36.0 ), 
    .\L.1 ( \n_36.1 ), 
    .\L.e ( \n_36_42.e ), 
    .\R.0 ( \n_36_FX1.0 ), 
    .\R.1 ( \n_36_FX1.1 ), 
    .\R.e ( \pchb_cfbuf_42_FX_inst_en0 ));
  \synthesis.qdi.special.CTREE4.2 \pchb_cfbuf_42_FX_inst_n_36_buf_companion0 ( 
    .x ( \pchb_cfbuf_42_FX_inst_en0 ), 
    .\a[0] ( \n_36_FX1_45.e ), 
    .\a[1] ( \c36.e ), 
    .\a[2] ( \c35.e ), 
    .\a[3] ( \c34.e ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cfbuf_43_FX_inst_Le_merge ( 
    .x ( \n_36_43.e ), 
    .\a[0] ( \pchb_cfbuf_43_FX_inst_n_36_0e ), 
    .\a[1] ( \pchb_cfbuf_43_FX_inst_n_36_1e ));
  \synthesis.qdi.special.CTREE4.2 \pchb_cfbuf_43_FX_inst_Re_a_merge ( 
    .x ( \pchb_cfbuf_43_FX_inst_en0 ), 
    .\a[0] ( \c33.e ), 
    .\a[1] ( \c32.e ), 
    .\a[2] ( \c31.e ), 
    .\a[3] ( \c30.e ));
  \synthesis.qdi.special.CTREE4.2 \pchb_cfbuf_43_FX_inst_Re_b_merge ( 
    .x ( \pchb_cfbuf_43_FX_inst_en1 ), 
    .\a[0] ( \c29.e ), 
    .\a[1] ( \c28.e ), 
    .\a[2] ( \c27.e ), 
    .\a[3] ( \c26.e ));
  \synthesis.qdi.special.BUF.6 \pchb_cfbuf_43_FX_inst_n_36_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \n_36.0 ), 
    .\L.1 ( \n_36.1 ), 
    .\L.e ( \pchb_cfbuf_43_FX_inst_n_36_0e ), 
    .\R.0 ( \n_36_FX2_a.0 ), 
    .\R.1 ( \n_36_FX2_a.1 ), 
    .\R.e ( \pchb_cfbuf_43_FX_inst_en0 ));
  \synthesis.qdi.special.BUF.6 \pchb_cfbuf_43_FX_inst_n_36_buf2 ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \n_36.0 ), 
    .\L.1 ( \n_36.1 ), 
    .\L.e ( \pchb_cfbuf_43_FX_inst_n_36_1e ), 
    .\R.0 ( \n_36_FX2_b.0 ), 
    .\R.1 ( \n_36_FX2_b.1 ), 
    .\R.e ( \pchb_cfbuf_43_FX_inst_en1 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cfbuf_44_FX_inst_Le_merge ( 
    .x ( \n_36_44.e ), 
    .\a[0] ( \pchb_cfbuf_44_FX_inst_n_36_0e ), 
    .\a[1] ( \pchb_cfbuf_44_FX_inst_n_36_1e ));
  \synthesis.qdi.special.CTREE3.2 \pchb_cfbuf_44_FX_inst_Re_a_merge ( 
    .x ( \pchb_cfbuf_44_FX_inst_en0 ), 
    .\a[0] ( \c25.e ), 
    .\a[1] ( \c24.e ), 
    .\a[2] ( \c23.e ));
  \synthesis.qdi.special.CTREE4.2 \pchb_cfbuf_44_FX_inst_Re_b_merge ( 
    .x ( \pchb_cfbuf_44_FX_inst_en1 ), 
    .\a[0] ( \c22.e ), 
    .\a[1] ( \c21.e ), 
    .\a[2] ( \c20.e ), 
    .\a[3] ( \c19.e ));
  \synthesis.qdi.special.BUF.6 \pchb_cfbuf_44_FX_inst_n_36_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \n_36.0 ), 
    .\L.1 ( \n_36.1 ), 
    .\L.e ( \pchb_cfbuf_44_FX_inst_n_36_0e ), 
    .\R.0 ( \n_36_FX3_a.0 ), 
    .\R.1 ( \n_36_FX3_a.1 ), 
    .\R.e ( \pchb_cfbuf_44_FX_inst_en0 ));
  \synthesis.qdi.special.BUF.6 \pchb_cfbuf_44_FX_inst_n_36_buf2 ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \n_36.0 ), 
    .\L.1 ( \n_36.1 ), 
    .\L.e ( \pchb_cfbuf_44_FX_inst_n_36_1e ), 
    .\R.0 ( \n_36_FX3_b.0 ), 
    .\R.1 ( \n_36_FX3_b.1 ), 
    .\R.e ( \pchb_cfbuf_44_FX_inst_en1 ));
  \synthesis.qdi.special.BUF.2 \pchb_cfbuf_45_SX_inst_n_36_FX1_buf ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \n_36_FX1.0 ), 
    .\L.1 ( \n_36_FX1.1 ), 
    .\L.e ( \n_36_FX1_45.e ), 
    .\R.0 ( \n_36_FX1_SX0_iter2.0 ), 
    .\R.1 ( \n_36_FX1_SX0_iter2.1 ), 
    .\R.e ( \c17.e ));

endmodule
