

// Generated by cosim_wrapper.pl to be used for cosim

module special_split_cosim_wrapper(interface In, interface Out0, interface Out1, input _RESET);

 special_split special_split_expanded (In.e[0] , Out0.d[0][0] , Out0.d[1][0] , Out1.d[0][0] , Out1.d[1][0] , In.d[0][0] 
 , In.d[1][0] , Out0.e[0] , Out1.e[0] , _RESET );

endmodule

// Generated by E-GRAPH (EGS) v0.01

module special_split (\In_e , \Out0_d[0][0] , \Out0_d[1][0] , \Out1_d[0][0] , \Out1_d[1][0] , \In_d[0][0] , \In_d[1][0] , 
  \Out0_e , \Out1_e , _RESET );
  input  \In_d[0][0] , \In_d[1][0] , \Out0_e , \Out1_e , _RESET ;

  output \In_e , \Out0_d[0][0] , \Out0_d[1][0] , \Out1_d[0][0] , \Out1_d[1][0] ;

  wire   \In_e , \Out0_d[0][0] , \Out0_d[1][0] , \Out1_d[0][0] , \Out1_d[1][0] , \c0.e , \c1.e , \n_2.0 , \n_2.1 ;

  trireg \pchb_cloud_2_inst_en0 ;



  \synthesis.qdi.special.SEND_1of2.2 \pchb_cloud_0_inst_Out0_SEND.send.bits[0].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out0_e ), 
    .\E.1 ( \n_2.0 ), 
    .\E.0 ( \n_2.1 ), 
    .\E.e ( \c0.e ), 
    .\L[0].1 ( \n_2.0 ), 
    .\L[0].0 ( \n_2.1 ), 
    .\R.0 ( \Out0_d[0][0] ), 
    .\R.1 ( \Out0_d[1][0] ));
  \synthesis.qdi.special.SEND_1of2.2 \pchb_cloud_1_inst_Out1_SEND.send.bits[0].send ( 
    ._RESET ( _RESET ), 
    .\R.e ( \Out1_e ), 
    .\E.0 ( \n_2.0 ), 
    .\E.1 ( \n_2.1 ), 
    .\E.e ( \c1.e ), 
    .\L[0].0 ( \n_2.0 ), 
    .\L[0].1 ( \n_2.1 ), 
    .\R.0 ( \Out1_d[0][0] ), 
    .\R.1 ( \Out1_d[1][0] ));
  \synthesis.qdi.special.BUF.4 \pchb_cloud_2_inst_In_RECEIVE.recv.bits[0].recv ( 
    ._RESET ( _RESET ), 
    .\L.0 ( \In_d[0][0] ), 
    .\L.1 ( \In_d[1][0] ), 
    .\L.e ( \In_e ), 
    .\R.0 ( \n_2.0 ), 
    .\R.1 ( \n_2.1 ), 
    .\R.e ( \pchb_cloud_2_inst_en0 ));
  \synthesis.qdi.special.CTREE2.2 \pchb_cloud_2_inst_In_RECEIVE.recv.bits[0].recv_companion0 ( 
    .x ( \pchb_cloud_2_inst_en0 ), 
    .\a[0] ( \c0.e ), 
    .\a[1] ( \c1.e ));

endmodule
